name: CMake Linux Build

on: [push, pull_request, workflow_dispatch]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: 'true'

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Restore/cache vcpkg's built packages
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
            doNotUpdateVcpkg: true

      - name: Configure CMake
        run: cmake --preset linux

      - name: Build
        run: cmake --build --preset linux

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BeamMP-Launcher
          path: ${{github.workspace}}/build/BeamMP-Launcher
